---
# tasks file for ansible-role-kibana

- name: Include vars/ansible_os_family.yml
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Include configure-{{ ansible_os_family }}.yml"
  include: "configure-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ kibana_log_dir }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    state: directory

- name: Configure kibana.yml
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_config_file }}"
    mode: 0644
  notify: Restart kibana

- name: Enable kibana
  service:
    name: "{{ kibana_service }}"
    enabled: yes

- name: Start kibana
  service:
    name: "{{ kibana_service }}"
    state: started
  register: register_kibana_start

- name: Wait for kibana to start in task
  wait_for:
    host: "{{ kibana_listen_host }}"
    port: "{{ kibana_listen_port }}"
  when:
    - register_kibana_start.changed
