---
# handlers file for ansible-role-kibana

- name: Restart kibana
  service:
    name: "{{ kibana_service }}"
    state: restarted
  notify: Wait for kibana to start

- name: Wait for kibana to start
  wait_for:
    host: "{{ kibana_listen_host }}"
    port: "{{ kibana_listen_port }}"
